/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;
import java.sql.*; 
import oracle.jdbc.*;
import oracle.sql.*; 
import java.awt.Color;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import Con_OOP.*; 
import java.util.List;
import javax.persistence.Query;
import javax.swing.*; 


/**
 *
 * @author Momen
 */
public class AddClient extends javax.swing.JFrame {

    /**
     * Creates new form deleteEmployee
     */
    public AddClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10UP = new javax.swing.JPanel();
        jLabel32UP = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel10UP1 = new javax.swing.JPanel();
        jLabel32UP1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(795, 565));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10UP.setBackground(new java.awt.Color(21, 21, 21));
        jPanel10UP.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 4, 1, new java.awt.Color(102, 102, 102)));
        jPanel10UP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32UP.setFont(new java.awt.Font("American Typewriter", 3, 24)); // NOI18N
        jLabel32UP.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32UP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32UP.setText("Save");
        jLabel32UP.setAutoscrolls(true);
        jLabel32UP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32UPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel32UPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel32UPMouseExited(evt);
            }
        });
        jPanel10UP.add(jLabel32UP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 60));

        getContentPane().add(jPanel10UP, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 260, 60));

        jLabel18.setFont(new java.awt.Font("STSong", 2, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Add Client information");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 490, 90));

        jLabel9.setFont(new java.awt.Font("Apple Chancery", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("SSN");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 60, 30));

        jTextField1.setBackground(new java.awt.Color(51, 51, 51));
        jTextField1.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 5, 1, new java.awt.Color(255, 0, 51)));
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 180, 30));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_search_property_40px.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 40, 30));

        jLabel3.setFont(new java.awt.Font("Apple Chancery", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Name ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 50, 30));

        jTextField2.setBackground(new java.awt.Color(51, 51, 51));
        jTextField2.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 5, 1, new java.awt.Color(255, 0, 51)));
        jTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField2.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 180, 30));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_name_40px.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Apple Chancery", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Phone ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, 30));

        jTextField3.setBackground(new java.awt.Color(51, 51, 51));
        jTextField3.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 5, 1, new java.awt.Color(255, 0, 51)));
        jTextField3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField3.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 180, 30));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_phone_40px.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Apple Chancery", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Address ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 70, 30));

        jTextField4.setBackground(new java.awt.Color(51, 51, 51));
        jTextField4.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 5, 1, new java.awt.Color(255, 0, 51)));
        jTextField4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField4.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 180, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_address_40px.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, -1, -1));

        jLabel12.setFont(new java.awt.Font("Apple Chancery", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Passowrd ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 80, 30));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_name_40px.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, 50));

        jPasswordField1.setBackground(jTextField3.getBackground());
        jPasswordField1.setFont(jTextField2.getFont());
        jPasswordField1.setForeground(jTextField4.getForeground());
        jPasswordField1.setToolTipText("");
        jPasswordField1.setBorder(jTextField1.getBorder());
        jPasswordField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 180, 30));

        jPanel10UP1.setBackground(new java.awt.Color(21, 21, 21));
        jPanel10UP1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 4, 1, new java.awt.Color(102, 102, 102)));
        jPanel10UP1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32UP1.setFont(new java.awt.Font("American Typewriter", 3, 24)); // NOI18N
        jLabel32UP1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32UP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32UP1.setText("Update");
        jLabel32UP1.setAutoscrolls(true);
        jLabel32UP1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32UP1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel32UP1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel32UP1MouseExited(evt);
            }
        });
        jPanel10UP1.add(jLabel32UP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 60));

        getContentPane().add(jPanel10UP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 260, 60));

        jLabel1.setFont(new java.awt.Font("American Typewriter", 3, 13)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wp3470526.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 875, 565));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel32UPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32UPMouseEntered
        jPanel10UP.setBackground(new Color(255,0,51));
    }//GEN-LAST:event_jLabel32UPMouseEntered

    private void jLabel32UPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32UPMouseExited
        jPanel10UP.setBackground(new Color(21,21,21));
    }//GEN-LAST:event_jLabel32UPMouseExited

    private void jLabel32UP1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32UP1MouseEntered
        jPanel10UP1.setBackground(new Color(255,0,51));
    }//GEN-LAST:event_jLabel32UP1MouseEntered

    private void jLabel32UP1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32UP1MouseExited
        jPanel10UP1.setBackground(new Color(21,21,21));
    }//GEN-LAST:event_jLabel32UP1MouseExited

    private void jLabel32UPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32UPMouseClicked
        // TODO add your handling code here:
        try {
        Con_OOP.Client c =new  Con_OOP.Client(); 
        c.setClientSsn(Integer.parseInt(jTextField1.getText()));
        c.setName(jTextField2.getText()); 
        c.setPhone(Long.parseLong(jTextField3.getText()));
        c.setAddress(jTextField4.getText());
        c.setPassword(jPasswordField1.getText());
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("ONEWAY_PROJECTPU");
        EntityManager em =emf.createEntityManager();
        em.getTransaction().begin();
        em.persist(c);
        em.getTransaction().commit();
        em.close();
        JOptionPane.showMessageDialog(null,"Add Client Successfully");
        }
        catch(Exception e )
        {
            JOptionPane.showMessageDialog(null,"Please Try again and cheack your information");
           
        }
    }//GEN-LAST:event_jLabel32UPMouseClicked
Con_OOP.Client foundUpdate =null; 
    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked

//"Client.findAll"
try {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("ONEWAY_PROJECTPU");
        EntityManager em =emf.createEntityManager();
        Query qry =em.createNamedQuery("Client.findAll"); //
        List < Con_OOP.Client> AllC =qry.getResultList(); 
        boolean flag =false ; 
        for(Con_OOP.Client c : AllC)
        {
            if(c.getClientSsn() == Integer.parseInt(jTextField1.getText()) )
            {
                foundUpdate =c ; 
                flag =true ; 
                jTextField1.setText(c.getClientSsn().toString());
                jTextField2.setText(c.getName());
                jTextField3.setText(c.getPhone().toString());
                jTextField4.setText(c.getAddress());
                jPasswordField1.setText(c.getPassword());
                break; 
                
            }
        }
        
        if(!flag) 
        {
            JOptionPane.showMessageDialog(null,"Not found the Client");
            foundUpdate =null; 
        }
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,"Please Try again and cheack your information");
}
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel32UP1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32UP1MouseClicked
        try{
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("ONEWAY_PROJECTPU");
        EntityManager em =emf.createEntityManager();
        Con_OOP.Client dd = em.find(Con_OOP.Client.class,foundUpdate.getClientSsn());
        em.getTransaction().begin();
        dd.setClientSsn(Integer.parseInt(jTextField1.getText()));
        dd.setName(jTextField2.getText()); 
        dd.setPhone(Long.parseLong(jTextField3.getText()));
        dd.setAddress(jTextField4.getText());
        dd.setPassword(jPasswordField1.getText());
        em.getTransaction().commit();
        em.close();
        JOptionPane.showMessageDialog(null,"Update Client Successfully");
        }
        catch(Exception e)
{
    JOptionPane.showMessageDialog(null,"Please Try again and cheack your information");
}
    }//GEN-LAST:event_jLabel32UP1MouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32UP;
    private javax.swing.JLabel jLabel32UP1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10UP;
    private javax.swing.JPanel jPanel10UP1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
