/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.persistence.TypedQuery;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Momen
 */
public class ShowClient extends javax.swing.JFrame {

    /**
     * Creates new form ShowClient
     */
    public ShowClient() {
        initComponents();
        jTable1.getTableHeader().setFont(new Font ("American Typewriter",Font.BOLD+Font.ITALIC ,22));
         jTable1.getTableHeader().setOpaque(false);
         jTable1.getTableHeader().setBackground(new Color(200,0,51));
         jTable1.getTableHeader().setForeground(new Color (255,255,255));
         jTable1.setRowHeight(25);
         jTable1.setEnabled(true);
         
        //Connection 
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("ONEWAY_PROJECTPU");
        EntityManager em =emf.createEntityManager();
        Query qry =em.createNamedQuery("Client.findAll"); //
        List < Con_OOP.Client> AllC =qry.getResultList(); 
        Object column [] ={"Client_SSN","Name","Phone","Address","Password"}; 
        DefaultTableModel model1 =new DefaultTableModel(new Object[0][0],column);
        
        for (Con_OOP.Client cc :  AllC )
        {
            Object[] o = new Object[5];
            o[0] = cc.getClientSsn();
            o[1] = cc.getName();
            o[2] = cc.getPhone();
            o[3] = cc.getAddress();
            o[4] = cc.getPassword();
            model1.addRow(o);
        }
        jTable1.setModel(model1);
         //
       
         jTable1.getTableHeader().setFont(new Font ("American Typewriter",Font.BOLD+Font.ITALIC ,22));
         jTable1.getTableHeader().setOpaque(false);
         jTable1.getTableHeader().setBackground(new Color(200,0,51));
         jTable1.getTableHeader().setForeground(new Color (255,255,255));
         jTable1.setRowHeight(25);
         jTable1.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel33 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel10UP1 = new javax.swing.JPanel();
        jLabel32UP1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setBackground(new java.awt.Color(255, 204, 204));
        jLabel33.setFont(new java.awt.Font("STSong", 3, 48)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel33.setText("Client Information");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, -10, 520, 200));

        jLabel9.setFont(new java.awt.Font("Apple Chancery", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Search by Name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 130, 30));

        jTextField1.setBackground(new java.awt.Color(51, 51, 51));
        jTextField1.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 5, 1, new java.awt.Color(255, 0, 51)));
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 180, 30));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_search_property_40px.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 175, 40, 40));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Client_SSN", "Name", "phone", "Address", "Password"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setSelectionBackground(new java.awt.Color(255, 153, 153));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowGrid(false);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 640, 220));

        jPanel10UP1.setBackground(new java.awt.Color(21, 21, 21));
        jPanel10UP1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 4, 1, new java.awt.Color(102, 102, 102)));
        jPanel10UP1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32UP1.setFont(new java.awt.Font("American Typewriter", 3, 24)); // NOI18N
        jLabel32UP1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32UP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32UP1.setText("Delete");
        jLabel32UP1.setAutoscrolls(true);
        jLabel32UP1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32UP1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel32UP1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel32UP1MouseExited(evt);
            }
        });
        jPanel10UP1.add(jLabel32UP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 60));

        getContentPane().add(jPanel10UP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 260, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MM.jpg"))); // NOI18N
        jLabel1.setName(""); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        //
        //
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("ONEWAY_PROJECTPU");
        EntityManager em =emf.createEntityManager();
        Query qry =em.createNamedQuery("Client.findByName"); //
        List < Con_OOP.Client> res =qry.setParameter("name",jTextField1.getText()).getResultList();
        if(res.isEmpty())
        {JOptionPane.showMessageDialog(null,"Not found result");}
        else{
        //table
        Object column [] ={"Client_SSN","Name","Phone","Address","Password"}; 
        DefaultTableModel model1 =new DefaultTableModel(new Object[0][0],column);
        
        for (Con_OOP.Client cc :  res )
        {
            Object[] o = new Object[5];
            o[0] = cc.getClientSsn();
            o[1] = cc.getName();
            o[2] = cc.getPhone();
            o[3] = cc.getAddress();
            o[4] = cc.getPassword();
            model1.addRow(o);
        }
        jTable1.setModel(model1);}
        //
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel32UP1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32UP1MouseEntered
        jPanel10UP1.setBackground(new Color(255,0,51));
    }//GEN-LAST:event_jLabel32UP1MouseEntered

    private void jLabel32UP1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32UP1MouseExited
        jPanel10UP1.setBackground(new Color(21,21,21));
    }//GEN-LAST:event_jLabel32UP1MouseExited

    private void jLabel32UP1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32UP1MouseClicked
       try {
       // System.out.println( jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0));
       EntityManagerFactory emf = Persistence.createEntityManagerFactory("ONEWAY_PROJECTPU");
        EntityManager em =emf.createEntityManager();
//        Query qry =em.createNamedQuery("delete.SSNClient"); //jTable1.getModel().getValueAt(jTable1.getSelectedRow(),0)
//        qry.setParameter("SSNCli","'adnan'");
//        qry.executeUpdate(); 
        Query qry1 =em.createNamedQuery("Client.findAll"); //
        List < Con_OOP.Client> AllC =qry1.getResultList();
        for(Con_OOP.Client vv : AllC)
        {
            if(vv.getClientSsn() == jTable1.getModel().getValueAt(jTable1.getSelectedRow(),0))
            {
                Con_OOP.Client dd = em.find(Con_OOP.Client.class,vv.getClientSsn());
                em.getTransaction().begin();
                em.remove(dd);
                em.getTransaction().commit();
                ////////////////////////////////////////////////////////////
                Query qry2 =em.createNamedQuery("Client.findAll");
                List < Con_OOP.Client> res =qry1.getResultList();
                 Object column [] ={"Client_SSN","Name","Phone","Address","Password"}; 
        DefaultTableModel model1 =new DefaultTableModel(new Object[0][0],column);
        
        for (Con_OOP.Client cc :  res )
        {
            Object[] o = new Object[5];
            o[0] = cc.getClientSsn();
            o[1] = cc.getName();
            o[2] = cc.getPhone();
            o[3] = cc.getAddress();
            o[4] = cc.getPassword();
            model1.addRow(o);
        }
        jTable1.setModel(model1);
                ///////////////////////////////////////////////////////////
                em.close();
                JOptionPane.showMessageDialog(null,"Delete Client Successfully");
                
                //table
                
                
                
                //
            }
        }
       }
       catch( Exception e )
       {
           JOptionPane.showMessageDialog(null,"Please Try again ,Select one row ");
       }
    }//GEN-LAST:event_jLabel32UP1MouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel32UP1;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10UP1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
