/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;
import java.sql.*; 
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import oracle.jdbc.*;
import oracle.sql.*; 

/**
 *
 * @author MMM
 */
public class Sign_IN extends javax.swing.JFrame {

    /**
     * Creates new form Sign_IN
     */
    public Sign_IN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Apple Chancery", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, 50));

        jLabel9.setFont(new java.awt.Font("Apple Chancery", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("SSN");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 100, 50));

        jPasswordField1.setBackground(new java.awt.Color(51, 51, 51));
        jPasswordField1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 5, 1, new java.awt.Color(251, 0, 51)));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 290, 50));

        jTextField1.setBackground(new java.awt.Color(51, 51, 51));
        jTextField1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 5, 1, new java.awt.Color(255, 0, 51)));
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 290, 50));

        jLabel7.setFont(new java.awt.Font("Zapfino", 3, 40)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Welcome to OneWay");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 570, 120));

        jButton1.setFont(new java.awt.Font("American Typewriter", 3, 36)); // NOI18N
        jButton1.setText("Log in");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 200, 50));

        jLabel1.setFont(new java.awt.Font("American Typewriter", 3, 13)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wp3470526.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 875, 565));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try
{
    boolean found =false ; 
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("ONEWAY_PROJECTPU");
        EntityManager em =emf.createEntityManager();
        
        Query qry =em.createNamedQuery("Employee.findManagerBySsn"); 
        List < Con_OOP.Employee> ES =qry.setParameter("ssn",Integer.parseInt(jTextField1.getText())).getResultList();
        
        Query qry1 =em.createNamedQuery("Employee.findCasherBySsn"); 
        List < Con_OOP.Employee> CAS =qry1.setParameter("ssn",Integer.parseInt(jTextField1.getText())).getResultList();
       
        Query qry2 =em.createNamedQuery("Client.findByClientSsn"); 
        List < Con_OOP.Client> CLS =qry2.setParameter("clientSsn",Integer.parseInt(jTextField1.getText())).getResultList();
        if(!ES.isEmpty())
        {
            Con_OOP.Employee m =ES.get(0); 
            if(m.getPassword().equals(jPasswordField1.getText()))
            {
                Maneger o =new Maneger(m); 
                o.setVisible(true);
                this.setVisible(false);
            }
            else 
            {
                JOptionPane.showMessageDialog(null,"Please Try again and cheack your information");
            }
            
        }
        else if (!CAS.isEmpty())
        {
             Con_OOP.Employee ca =CAS.get(0);
             if(ca.getPassword().equals(jPasswordField1.getText()))
            {
                 Casher h =new Casher (ca); 
                 h.setVisible(true);
                  this.setVisible(false);
            }
            else 
            {
                JOptionPane.showMessageDialog(null,"Please Try again and cheack your information");
            }
        }
        else if(!CLS.isEmpty()) 
        {
            Con_OOP.Client cl =CLS.get(0); 
            if(cl.getPassword().equals(jPasswordField1.getText()))
            {
                Client m =new Client(cl); 
                m.setVisible(true);
                 this.setVisible(false);
            }
            else 
            {
                JOptionPane.showMessageDialog(null,"Please Try again and cheack your information");
            }
        }
        else 
        {
            JOptionPane.showMessageDialog(null,"Please Try again and cheack your information");
        }
        
}
catch(Exception ex)
{
    JOptionPane.showMessageDialog(null,"Please Try again and cheack your information");
    //ex.printStackTrace();
}        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
